config/routes.rb
Zinc::Application.routes.draw do

  resources :rooms
  resources :r, :controller => "rooms"

  resources :user_sessions
  resources :users

  get "logout" => "user_sessions#destroy", :as => "logout"
  get "login"  => "user_sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"

  root :to => 'pages#landing'
end

app/views/layouts/application.haml
!!! 5
%html
  %head
    %meta{:charset => "UTF-8"}
    %title Zinctub
    = stylesheet_link_tag "application", :media => "all"
    = include_gon(:namespace => "Zinc", :init => true)
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .header-container
      .row
        = link_to :root, class: "logo" do
          %span.logo-image
            = image_tag "zinctub.png"
          %span.logo-text Zinctub
        - if @room
          %span.room-name= "r/#{@room.slug}"

        .header-actions
          %ul.vertical-action-list
            - if current_user
              - unless current_user.is?(:owner, Room)
                %li= icon_link_to "Create Room", new_room_path, icon: "asterisk", class: "btn btn-primary"

              %li= link_to "Rooms", rooms_path, class: "btn"

              %li= icon_link_to current_user.username, edit_user_path(current_user), icon: "user", class: "btn"
              %li= icon_link_to "", :logout, icon: "signout", class: "btn"

            - else
              %li= link_to "Signup", new_user_path, class: "btn btn-primary"
              %li= link_to "Rooms", rooms_path, class: "btn"
              %li= icon_link_to "Login", :login, icon: "signin", class: "btn"

    = yield
    %ul.browl-container